CREATE USER LHASTING;

GRANT SELECT, CREATE, ALTER
TO LHASTING
WITH GRANT OPTION;

CREATE ROLE CUSTOMERREP;
GRANT INSERT, DROP
ON ORDERS, ORDERITEMS 
TO CUSTOMERREP;

GRANT CUSTOMERREP TO LHASTING;

REVOKE DROP FROM CUSTOMERREP;

REVOKE CUSTOMERREP FROM LHASTING;

DROP ROLE CUSTOMERREP;

DROP USER LHASTING;